[theme]
primaryColor = "#4A90E2"            # A fresh blue as the primary color
backgroundColor = "#F7F9FB"         # A soft, light-gray background for better contrast
secondaryBackgroundColor = "#E3E8F0" # Slightly darker shade for secondary elements
textColor = "#1B5E20"                # Dark green for text
font = "serif"                       # Serif font for a more professional, classic look

[global]
showWarningOnDirectExecution = false

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false


